In [1]:
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [65]:
import numpy as np

# Sample data (replace with your actual data)
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])

daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])



# Calculate the total sales revenue for all products combined


In [66]:
# Calculate total sales revenue for each product over the past week
p=np.sum(daily_sales_data, axis=(1))
p

array([175,  72, 205, 204, 210])

In [67]:
# Calculate average daily sales for each product
d=np.mean(daily_sales_data, axis=(1))
d

array([25.        , 10.28571429, 29.28571429, 29.14285714, 30.        ])

In [68]:
# Find the product with the  lowest sales
np.max(p)


210

In [69]:
# Find the product with the  lowest sales
np.min(p)


72

In [70]:
np.sum(p)

866

# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [75]:


# Sample data (replace with your actual data)


# Generate random production rates between 100 and 200 for 5 machines and 30 days
 # For reproducibility
production_rates = np.random.randint(100, 201, size=(5, 30))
print(production_rates)



print('---------------------------------------------------')

# Calculate total production output for each machine over the past month
g=np.sum(production_rates, axis=1)
print("total production:", g)

print(  "---------------------------------------------")

# Calculate average daily production rate for each machine
h=np.mean(production_rates, axis=1)
print("average daily production:",h)

print('---------------------------------------------')


# Find the machine with the highest and lowest total production output
gg=np.max(g)
print("machine with the highest total production:",  gg)

hh=np.min(g)
print("machine with the lowest total production :" ,hh)


print('-----------------------------------------')

# Calculate the overall production efficiency of the plant
overall_efficiency = np.sum(g) / (2 * 30)
print("Overall Production Efficiency:", overall_efficiency)

[[144 147 164 167 167 109 183 121 136 187 170 188 188 112 158 165 139 187
  146 188 181 137 125 177 172 109 120 180 169 179]
 [147 164 182 199 188 149 129 119 119 114 139 132 165 109 157 132 131 174
  123 135 175 155 128 134 100 100 136 153 105 138]
 [117 179 104 142 158 131 101 165 141 157 135 111 146 182 191 100 114 199
  153 112 142 184 175 168 106 168 147 103 176 200]
 [152 178 115 120 199 158 123 179 113 185 148 149 169 141 135 164 195 169
  194 100 150 136 134 148 193 103 198 142 177 121]
 [173 100 110 143 158 123 159 102 198 162 135 194 167 182 146 199 120 181
  150 127 114 141 158 165 136 110 186 143 111 102]]
---------------------------------------------------
total production: [4715 4231 4407 4588 4395]
---------------------------------------------
average daily production: [157.16666667 141.03333333 146.9        152.93333333 146.5       ]
---------------------------------------------
machine with the highest total production: 4715
machine with the lowest total production : 4

# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [38]:
import numpy as np

# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)

# Generate Random Sensor Data
sensor_data = np.random.uniform(0.0, 100.0, size=shape)
print(sensor_data)

[[95.01924682 99.44959314 37.44948995 ... 25.32614587 86.77099685
  42.66083387]
 [26.78289392 69.28137627  5.1228404  ... 10.30687507 83.63946423
  45.26384465]
 [12.43872666 15.59204842 61.1422736  ... 29.33689159  1.18136372
   9.40238805]
 ...
 [29.42685428 78.36367417 64.19142502 ... 61.55111211 98.50488848
  58.9100485 ]
 [65.23451546 28.84891659 32.5851408  ... 87.9364097  14.34079202
   3.0643464 ]
 [ 6.09510945 52.21851641 21.52486712 ...  7.22857614 17.11346041
  63.4156407 ]]


In [58]:
# 1.Calculate the mean (average) sensor reading for each sensor over the 15 days.
m=np.mean(sensor_data, axis=1)
print(m)

[45.89592308 49.87681132 48.21629908 48.37938626 49.92153865 50.50818297
 47.57671533 50.2496202  49.04699643 48.32466256]


In [39]:
#2.Calculate the standard deviation of sensor readings for each sensor.
s=np.std(sensor_data, axis=1)
print(s)

[28.08663934 27.86345581 27.92698046 28.182531   28.97575648 29.6485831
 28.97370483 27.36613827 29.69521552 28.88951207]


In [40]:
#3.Calculate the maximum sensor reading for each sensor.
f=np.max(sensor_data)
print(f)

99.99566127577249


In [42]:
# 4.Calculate the minimum sensor reading for each sensor.
k=np.min(sensor_data)
print(k)

0.0072449638492178


In [43]:
#5.Calculate the overall mean sensor reading for all sensors and all days.
v=np.mean(sensor_data)
print(v)

48.79961358894359


In [46]:
#6.Calculate the overall standard deviation of sensor readings for all sensors an
sn=np.std(sensor_data)
print(sn)

28.602443710619628


# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [78]:
import numpy as np

# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10

# Populate the exam_scores array with random scores between 50 and 100
exam=np.random.randint(50,100,(num_students,num_exams))
print(exam)

# 1. Calculate the average score for each student over the 10 exams
k=np.mean(exam,axis=1)
print(k)



# 2. Calculate the standard deviation of scores for each student
mn=np.std(exam,axis=1)
print(mn)


# 3. Identify students who have consistently performed well (average score > 85)

performing_well_indices = np.where(k > 85)[0]
print("Students who have consistently performed well (average score > 85):")
print(f"Indices: {performing_well_indices.tolist()}")




# 4. Identify students who may need additional support (average score < 60)
need_support_indices = np.where(k < 60)[0]

print("\nStudents who may need additional support (average score < 60):")
print(f"Indices: {need_support_indices.tolist()}")

[[60 70 92 51 70 66 92 78 76 73]
 [98 52 88 59 52 94 91 75 86 76]
 [54 91 60 62 90 83 87 89 82 83]
 [76 85 75 74 68 70 80 78 58 68]
 [75 74 89 92 78 74 68 53 94 69]
 [95 50 60 53 56 77 85 56 69 84]
 [88 70 93 50 86 95 91 52 83 62]
 [65 83 73 62 55 88 51 60 56 56]
 [88 88 61 71 52 62 79 59 58 55]
 [93 51 93 65 62 97 62 71 68 75]
 [63 80 78 94 91 71 56 86 98 90]
 [76 80 55 65 87 87 99 81 82 98]
 [66 82 60 62 79 50 79 76 89 72]
 [69 55 86 69 86 55 78 62 76 99]
 [69 62 88 57 66 79 50 73 65 60]
 [53 53 66 98 59 70 87 98 67 59]
 [94 65 88 64 83 54 66 86 57 73]
 [77 96 57 72 84 80 66 77 97 97]
 [61 73 64 89 80 76 84 67 85 57]
 [95 98 87 54 63 87 69 93 58 82]
 [67 55 86 51 79 55 66 88 90 72]
 [80 69 54 70 92 60 53 72 87 79]
 [91 90 67 90 92 80 79 83 80 96]
 [87 74 66 85 89 79 51 73 58 50]
 [73 87 97 76 75 75 56 74 65 87]
 [91 67 66 98 93 96 55 69 97 72]
 [95 61 61 83 57 76 98 57 97 82]
 [86 68 73 71 52 58 60 55 88 88]
 [86 51 86 55 55 88 85 74 99 65]
 [70 59 54 99 74 80 52 69 53 63]]
[72.8 77.