In [2]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [5]:
# Answer Here
arr=np.empty((2,3,4))
arr
arr.sum()

9.054372561801604e+271

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [21]:
# Answer Here
arr=np.random.randint(0,10, size=(2,3,4,5))
arr

array([[[[0, 1, 6, 0, 9],
         [1, 9, 8, 0, 1],
         [3, 0, 1, 1, 6],
         [5, 0, 7, 3, 0]],

        [[2, 3, 7, 2, 1],
         [8, 9, 0, 4, 1],
         [3, 6, 5, 1, 6],
         [8, 7, 0, 3, 3]],

        [[4, 4, 2, 4, 5],
         [4, 0, 6, 4, 9],
         [9, 3, 8, 1, 9],
         [8, 3, 1, 9, 4]]],


       [[[3, 6, 0, 5, 3],
         [7, 0, 6, 7, 5],
         [7, 3, 2, 8, 2],
         [9, 7, 0, 9, 7]],

        [[1, 4, 6, 8, 9],
         [7, 5, 3, 2, 1],
         [1, 2, 7, 4, 8],
         [6, 7, 7, 0, 9]],

        [[2, 6, 5, 6, 1],
         [0, 9, 2, 1, 9],
         [0, 8, 1, 7, 8],
         [5, 6, 4, 9, 6]]]])

In [39]:
3=np.arange(120).reshape(2,3,4,5)
arr

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [26]:
# Answer Here
arr=np.empty((2,3,4,5))
arr

arr.mean(axis=2)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [30]:
arr=np.empty((7,24,60))
arr
np.mean(arr, axis=(1,2))
# Answer Here

array([6.84340224e-303, 2.08773793e-311, 1.37501033e-301, 2.11178825e-311,
       4.31267780e-272, 1.03104854e-311, 2.67787807e-312])

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [36]:
# Answer Here

arr=np.empty((4,7,24,60))
np.max(arr,axis=(1,2,3))

array([4.90900643e+252,             nan, 0.00000000e+000, 0.00000000e+000])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [63]:

dimensions = np.random.rand(100, 50, 3)  # Example data

# Calculate the average length, width, and height across all objects
average_dimensions = np.mean(dimensions, axis=(0, 1))

# Extract the individual averages
average_length = average_dimensions[0]
average_width = average_dimensions[1]
average_height = average_dimensions[2]

print(f"Average Length: {average_length}")
print(f"Average Width: {average_width}")
print(f"Average Height: {average_height}")


Average Length: 0.504200736948895
Average Width: 0.5055431453858892
Average Height: 0.5002330942616768


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [47]:
# Answer Here
arr=np.arange(210).reshape(5,6,7)

In [48]:
arr

array([[[  0,   1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41]],

       [[ 42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76],
        [ 77,  78,  79,  80,  81,  82,  83]],

       [[ 84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97],
        [ 98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125]],

       [[126, 127, 128, 129, 130, 131, 132],
        [133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146],
        [147, 148, 149, 150, 151, 152, 153],
    

In [57]:
np.size(arr)

210

In [58]:
np.mean(arr)

104.5

In [59]:
np.std(arr)

60.621090939265244

In [60]:
np.min(arr)

0

In [61]:
np.max(arr)

209