In [ ]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [2]:
# Answer Here

list = ["A" , "B" , "C", "D" , "E"]
print(list)

['A', 'B', 'C', 'D', 'E']


In [6]:
list = [1,2,3,4,5,6]
list

[1, 2, 3, 4, 5, 6]

In [4]:
#length
len(list)

6

# Type
Accuire type of list in python.

In [8]:
# Answer Here
mylist= ["ali", "hamza" , "zubair" , "muhsin"]
print(type(mylist))

<class 'list'>


# Creatation of Arrays
1.Simple array creation

2.Checking array "TYPE"

3.Numeric "TYPE" of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [9]:
import numpy as np

1.Simple array creation

In [21]:
# Int array
array=np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

2.Checking array "TYPE"

In [12]:
print(type(array))

<class 'numpy.ndarray'>


3.Numeric "TYPE" of array elements

In [15]:
element_type= array.dtype
print(element_type)

int32


4. Array dimension

In [16]:
array_dim=array.ndim
print(array_dim)

1


5. Array Shape

In [17]:
array_shape=array.shape
print(array_shape)

(5,)


6. Bytes per element

In [18]:
bytes_per_element = array.itemsize
print(bytes_per_element)

4


7. BYTES OF MEMORY USED, How many bytes for one array element

In [19]:
bytes_per_element = array.itemsize
print(bytes_per_element)

4


8. Total bytes in an Array

In [20]:
total_bytes=array.nbytes
print(total_bytes)

20


In [23]:
# Decimal array


decimal_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
decimal_array

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [28]:
# Checking array "TYPE"
decimal_array_type = type(decimal_array)
print(decimal_array_type)

<class 'numpy.ndarray'>


In [29]:
# Numeric "TYPE" of array elements
decimal_element_type = decimal_array.dtype
print(decimal_element_type)

float64


In [30]:
# Array dimension
decimal_array_dim = decimal_array.ndim
print(decimal_array_dim)


1


In [31]:
# Array Shape
decimal_array_shape = decimal_array.shape
print(decimal_array_shape)

(5,)


In [34]:
# Bytes per element
decimal_bytes_per_element = decimal_array.itemsize
print(decimal_bytes_per_element)

8


In [33]:
# Total bytes in an Array
decimal_total_bytes = decimal_array.nbytes
print(decimal_total_bytes)

40


9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


9.Try to assign a float into an int32

In [36]:
array=np.array([1,2,3,4,5],dtype=np.int32)
array[0]=3.14
array

array([3, 2, 3, 4, 5])

10.Use .fill function # fill has the same behavior

In [38]:
array=np.array([2,4,6,8],dtype=np.int32)
array.fill(1)
array

array([1, 1, 1, 1])

In [ ]:
# Answer here

11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [ ]:
# Answer Here


11.Add two arrays

In [40]:
array1=np.array([1,2,3,4])
array2=np.array([2,4,6,8])
array1+array2

array([ 3,  6,  9, 12])

12. Multiply Both Arrays

In [41]:
array1*array2

array([ 2,  8, 18, 32])

13. Use ** Operator in Array Operation

In [43]:
squared_array = array1 ** 2

print(squared_array)

[ 1  4  9 16]


14.Create array from 0.0 to 11.0

In [45]:
array=np.arange(11.0)
array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

15.Multiply entire array with a scalar value c = (2.0 * np.pi)

In [46]:
c = (2.0 * np.pi)

In [47]:
c*array

array([ 0.        ,  6.28318531, 12.56637061, 18.84955592, 25.13274123,
       31.41592654, 37.69911184, 43.98229715, 50.26548246, 56.54866776,
       62.83185307])

16.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [49]:
array=np.arange(1.0,3.5,0.5)
print(array)

[1.  1.5 2.  2.5 3. ]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [ ]:
# Answer Here

1. Extract Array Indices from 1 to 3

In [53]:
array=np.array([1,2,3,4,5,6])

In [55]:
array[1:4]

array([2, 3, 4])

2. Use Negative Indices

In [61]:
array[-4:-1]

array([3, 4, 5])

3.Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements

In [63]:
array=np.array([4,5,6,7,8,9])
array[:3]

array([4, 5, 6])

4. Grab Last Two Elements

In [65]:
array=np.array([100,200,300,400,500,600])
array[-2:]

array([500, 600])

5. Grab Every Other Element

In [67]:
array=np.array([100,200,300,400,500,600,700,800])
array[::2]

array([100, 300, 500, 700])

6. Slicing the Last Two Elements

In [68]:
array=np.array([100,200,300,400,500,600,700,800])
array[-2:]

array([700, 800])

8.if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5

In [ ]:
only two rows is here

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [ ]:
# Answer Here

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here

In [ ]:
#For loop to add corresponding elements in two lists

# Answer Here