# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [2]:
# Rule 1 PREPEND ONES TO SMALLER ARRAY'S SHAPE
import numpy as np
a=np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
b=np.ones((5,))
b

array([1., 1., 1., 1., 1.])

In [4]:
b.reshape(1,5)

array([[1., 1., 1., 1., 1.]])

In [5]:
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

In [6]:
b

array([1., 1., 1., 1., 1.])

In [7]:
# RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [8]:
c=a+b


In [9]:
c.shape==(3,5)

True

In [10]:
tmp_b=b.reshape(1,5)

In [11]:
tmp_b_repeat= tmp_b.repeat(3, axis=0)
c= a+tmp_b_repeat

In [12]:
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [13]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
# Using reduce to sum all elements in the array
sum_all = np.add.reduce(a)

In [15]:
sum_all

array([50, 55, 60, 65, 70])

In [16]:
## Using reduce to sum elements along axis 0 (column-wise)
sum_axis_0=np.add.reduce(a, axis=0)

In [17]:
sum_axis_0

array([50, 55, 60, 65, 70])

In [18]:
# Using accumulate to get intermediate sums of the array
accumulate_all = np.add.accumulate(a)

In [19]:
accumulate_all

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27],
       [30, 34, 38, 42, 46],
       [50, 55, 60, 65, 70]])

In [20]:
#Using accumulate to get intermediate sums along axis 0 (column-wise)
accumulate_axis_0=np.add.accumulate(a,axis=0)
accumulate_axis_0

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27],
       [30, 34, 38, 42, 46],
       [50, 55, 60, 65, 70]])

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [21]:
first_row = np.arange(10, 80, 5)
second_row = np.arange(5, 47, 3)
array_2d = np.vstack((first_row, second_row))
print(array_2d)


[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [22]:
import numpy as np
row1 = np.arange(10, 80, 5)
row2 = np.arange(5, 47, 3)
array_2d = np.array([row1, row2])
selected_columns = array_2d[:, [4, 6, 10]]
print(selected_columns)

[[30 40 60]
 [17 23 35]]


### Select the 2nd row and fourth-last to second-last columns

In [23]:

row1 = np.arange(10, 80, 5)
row2 = np.arange(5, 47, 3)
array_2d = np.array([row1, row2])

#(index -4 to -2)
selected_elements = array_2d[1, -4:-1]
print(selected_elements)


[35 38 41]


### Select 3rd to 3rd last columns skipping every second column

In [24]:
row1 = np.arange(10, 80, 5)
row2 = np.arange(5, 47, 3)
array_2d = np.array([row1, row2])

# index 2 to -3 with step 2
selected_columns = array_2d[:, 2:-3:2]

print(selected_columns)


[[20 30 40 50 60]
 [11 17 23 29 35]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [25]:
row1 = np.arange(10, 80, 5)
row2 = np.arange(5, 47, 3)
array_2d = np.array([row1, row2])
selected_columns_reverse = array_2d[:, -4:1:-2]
print(selected_columns_reverse)


[[60 50 40 30 20]
 [35 29 23 17 11]]


### We will work with the following array:

In [26]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [27]:
a[[2,4]][:,[1,4]]

array([[11, 14],
       [21, 24]])

In [28]:
a[2:5:2, 1:6:3]

array([[11, 14],
       [21, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [29]:
a[[0, 2, 4]][:, [2, 3]]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [30]:
# Answer here
subarray = a[[1, 2, 4]][:, [1, 3]]
subarray

array([[ 6,  8],
       [11, 13],
       [21, 23]])

### Change the values 1, 10, 19 and 22 in the array to -2

In [31]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
change = [1, 10, 19, 22]
a.flat[change] = -2
print(a)


[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [40]:
# Answer here
mask=np.isin(a,[1,10,19,22])
mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [55]:
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

In [54]:
# Answer here
subarray = a[[0, 2, 3]][:, [0, 3]]

subarray

array([[ 0,  3],
       [-2, 13],
       [15, 18]])

### Calculating the sum, min and max of all diagonal values

In [42]:
# Answer here
diagnoal_values = np.diag(a)
diagnoal_values

array([ 0,  6, 12, 18, 24])

In [43]:
sum=np.sum(diagnoal_values)
sum

60

In [44]:
min=np.min(diagnoal_values)
min

0

In [45]:
max=np.max(diagnoal_values)
max

24

### Create a new array that is the sum of even rows and odd rows

In [46]:
# Splitting into even and odd rows
even_rows = a[::2]  
odd_rows = a[1::2] 

sum_even_rows = np.sum(even_rows, axis=0)
sum_odd_rows = np.sum(odd_rows, axis=0)

new_array = np.array([sum_even_rows, sum_odd_rows])

print(new_array)


[[18 30 12 39 42]
 [20 22 24 26  7]]


In [51]:
even=a[::2]
odd=a[1::2]


In [52]:
print(even)

[[ 0 -2  2  3  4]
 [-2 11 12 13 14]
 [20 21 -2 23 24]]


In [53]:
print(odd)

[[ 5  6  7  8  9]
 [15 16 17 18 -2]]


## You are done. Good job!